### ISSUE TITLE
Real tab names are too long, and therefore overflow 

### ISSUE THREAD

**Issue by adam-grandt-tts** [adam-grandt-tts/data-driven-acquisition#17]
**Describe the bug**
Please visit https://datadrivenacquisition.app.cloud.gov/package/1/ to see the issues.

**To Reproduce**

1. 
2. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adunkman** [comment]
I can’t visit that URL, as I don’t have login information — could you post a screenshot?

**Comment by adunkman** [comment]
I noticed that in 13b7d8ebe6a3a146088fdcc46fd03057819c210e, the tabs changed in development: 

![image](https://user-images.githubusercontent.com/14930/73464480-0265f300-434d-11ea-974f-069fd6f75c97.png)

Are these the tabs you’re speaking about @adam-grandt-tts?

**Comment by adunkman** [comment]
Discussing this in person, we’ll move the tabs to the sidenav, and treat this form as a long-scrolling page.
