### ISSUE TITLE
Demystify “Save properties” and “Update content” buttons.

### ISSUE THREAD

**Issue by adunkman** [adam-grandt-tts/data-driven-acquisition#8]
There are two buttons associated with the Edit Package form, `Save properties` and `Update content`. It is not clear what the difference is between these, as they both seem to indicate submitting the form:

![Screenshot of package editor](https://user-images.githubusercontent.com/14930/72815519-c5a34900-3c34-11ea-8b41-484ce5dea816.png)

**Comment by adunkman** [comment]
Asked in Slack, and @adam-grandt-tts has informed me that “Save properties” submits the form and saves their values, but those values are not yet applied to the related acquisition files. “Update content” does that additional step — it takes the properties and applies them to the files in the package. 

We could add additional descriptions to these buttons to explain them, but I’d argue that the intermediary step — where the properties have been saved but not applied to the files — is an invalid state for the package to be in. I’d opt for applying the properties to the files immediately upon saving.

**Comment by adam-grandt-tts** [comment]
The fact that this requires demystification implies  this UX needs changing. 
Adding a ticket to add teh update content action to save properties.

**Comment by adunkman** [comment]
Replaced by #15.
